<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_skilldescription</name>
   <tag></tag>
   <elementGuidId>13319195-0b08-41a9-9e9f-67efcb79d14f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='skill_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#skill_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>43e5a8c8-f807-4320-a575-34b73e9beadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f835ac98-7426-48b7-9df6-a719302fbb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>00c48b14-35ba-4a57-95db-66ad2a6cad0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>skill[description]</value>
      <webElementGuid>3afd0280-5c0f-4a80-999b-a31717de610d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>5ae034f9-e543-4d5f-b600-f176f2c6ec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>skill_description</value>
      <webElementGuid>353dd3ee-d045-4c53-8c00-9d6a32c3cd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skill_description&quot;)</value>
      <webElementGuid>9f0bf723-a197-48e2-84b4-7b8907ddae0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='skill_description']</value>
      <webElementGuid>d5451804-d3fd-4123-ac4b-9d7f51459276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSave']/fieldset/ol/li[2]/textarea</value>
      <webElementGuid>e7ac24df-fb2e-4ea3-8956-59ff527b1105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cb24686e-a030-4aca-aec8-bfd3f4187002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'skill[description]' and @id = 'skill_description']</value>
      <webElementGuid>35ab97c9-ccc0-470f-8960-7fe0075d268a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
