<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__workShiftname</name>
   <tag></tag>
   <elementGuidId>9b8aea69-aa93-4210-8db8-3c98143767ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workShift_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workShift_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bb88c99-e99c-4992-800d-f3ea8012375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>290c6217-7077-4b7e-b5ac-92a84f44f481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35648063-d498-4ce0-a29b-ff39d3859ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workShift[name]</value>
      <webElementGuid>4d15bbe3-c54d-4bc7-bd24-f90baa09a779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workShift_name</value>
      <webElementGuid>ae762626-011c-4f92-a8d4-ed2b78a8f42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workShift_name&quot;)</value>
      <webElementGuid>4460646a-1bf9-41d5-9a26-ce71efb5e7ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workShift_name']</value>
      <webElementGuid>c5f6e92a-966f-4678-8d79-bc9649c217d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmWorkShift']/fieldset/ol/li/input</value>
      <webElementGuid>e39a5fce-b539-4d9b-a12f-e3dce27fbcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>0edcee28-dd95-407e-9096-faf27bc8ea7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'workShift[name]' and @id = 'workShift_name']</value>
      <webElementGuid>98416dc3-e0e1-4d19-a575-c874878f8340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
