<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_From time should be less than To time</name>
   <tag></tag>
   <elementGuidId>a1941654-4c2d-41eb-a02a-5e08e853c4b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmWorkShift']/fieldset/ol/li[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d9d2c1f-9e16-4168-967a-7f44c4c2d862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>workShift_workHours_from</value>
      <webElementGuid>031e609d-affe-4b02-aba7-e5a5a0f492d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19828165-7ee6-4c8a-b6ad-d315c106fd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-error</value>
      <webElementGuid>35d612ab-d0a1-41cf-8b73-089169c62cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>From time should be less than To time</value>
      <webElementGuid>c8bd9901-0638-4736-9408-2fd7158e2e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmWorkShift&quot;)/fieldset[1]/ol[1]/li[2]/span[@class=&quot;validation-error&quot;]</value>
      <webElementGuid>4576f90d-8bfe-46e6-b52c-431cef376344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmWorkShift']/fieldset/ol/li[2]/span</value>
      <webElementGuid>0950b7b3-77f2-45ea-8b0d-732693833677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::span[1]</value>
      <webElementGuid>cace5ee1-cad1-496e-b60e-1b390f24af7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[1]</value>
      <webElementGuid>970385ed-ef0c-436a-9863-38503438de53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/preceding::span[1]</value>
      <webElementGuid>568f51e9-dd79-47d1-bd30-55aea810e0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/preceding::span[1]</value>
      <webElementGuid>1db17d15-164a-489e-bb18-4daee58f790b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='From time should be less than To time']/parent::*</value>
      <webElementGuid>fc2453e2-0254-4cca-9ca8-91ba3b0dea56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>45da69f1-5fd6-4f60-8fd0-c935c67e343f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'From time should be less than To time' or . = 'From time should be less than To time')]</value>
      <webElementGuid>ec308e0a-1f7f-4d25-a9df-4af0a513f13c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
