<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_searchDirectoryemp_nameempName</name>
   <tag></tag>
   <elementGuidId>c11b0122-a5da-4eec-a4ea-44ac7f35f783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchDirectory_emp_name_empName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchDirectory_emp_name_empName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b9a74df-f667-41cd-a97f-1fcb1c9d9fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText ac_input</value>
      <webElementGuid>67f9031e-4b55-4ccf-95c7-f87c3741333a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e92e768-e316-4920-a65c-aac048e4e4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchDirectory[emp_name][empName]</value>
      <webElementGuid>1d7293aa-9824-4823-9b0b-9596a871f81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDirectory_emp_name_empName</value>
      <webElementGuid>d62fd574-8eaa-46e8-a50b-67a3418e4d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5f5a6c3c-e7dc-473c-b695-62fc1a669d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDirectory_emp_name_empName&quot;)</value>
      <webElementGuid>e5b8f60c-c9f0-4c2e-8373-abd687a4fc41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchDirectory_emp_name_empName']</value>
      <webElementGuid>ec514375-053c-475a-a6ca-70a1ae94307d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>477a9b42-e754-45bc-a3dd-b9a7207ba6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>ee53c74b-856e-4d9f-b908-8efb3f8af160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchDirectory[emp_name][empName]' and @id = 'searchDirectory_emp_name_empName']</value>
      <webElementGuid>2a9d593d-7eb4-4a69-803a-52137deba82c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
