<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Timesheet</name>
   <tag></tag>
   <elementGuidId>c061fe58-59de-4431-8303-ccf61ca2e673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddTimesheet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAddTimesheet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f242835f-ce86-41a2-adf8-c51023ada366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddTimesheet</value>
      <webElementGuid>0d6ae923-bc7f-46f6-ae0c-a471c24b0f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>72c4c27c-7d59-46e0-a88f-c4974e60482a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#createTimesheet</value>
      <webElementGuid>2e2f73f6-55ab-43ac-9f9b-04cf1e4118f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fieldHelpRight</value>
      <webElementGuid>83656177-f786-4fee-bae2-6de35dfb15d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Timesheet</value>
      <webElementGuid>210f198a-12d5-4cb8-a1b0-9ae3b09386b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddTimesheet&quot;)</value>
      <webElementGuid>774542e7-05f6-4b21-8ec1-ca3f272c1266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnAddTimesheet']</value>
      <webElementGuid>f5bb31c9-8675-4703-9ae6-b66227a70a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='timesheet']/div/div/form/ol/li/a</value>
      <webElementGuid>2cfba052-7096-442e-987f-130794ac3edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Timesheet')]</value>
      <webElementGuid>40ee782a-ffc0-460f-bc32-8b14e086d8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timesheet for Week'])[1]/following::a[1]</value>
      <webElementGuid>8cdb03d7-0cb1-443e-af31-fd0efae74940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buzz'])[1]/following::a[1]</value>
      <webElementGuid>270ea625-a3ea-4c8d-88f9-061778bb3b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Name'])[1]/preceding::a[1]</value>
      <webElementGuid>c3e53f81-76db-4598-aa7a-52ef4b0d2210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity Name'])[1]/preceding::a[1]</value>
      <webElementGuid>b23ff78c-b1c6-4e99-8467-8161dfb3e4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Timesheet']/parent::*</value>
      <webElementGuid>ad0ec2d1-bbd0-44f6-8f0f-1f0bcdc148f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#createTimesheet')]</value>
      <webElementGuid>645df40d-e1a1-4c95-9b7c-cc6420935faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/a</value>
      <webElementGuid>355f7be0-7aca-453d-9083-3f4eae1fc3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnAddTimesheet' and @href = '#createTimesheet' and (text() = 'Add Timesheet' or . = 'Add Timesheet')]</value>
      <webElementGuid>31d6cc3c-776a-4a75-8fe1-8bd100dbdf0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
