<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Employee Trackers</name>
   <tag></tag>
   <elementGuidId>24ad549c-7f33-4644-8a64-100b322b0001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_performance_viewEmployeePerformanceTrackerList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_performance_viewEmployeePerformanceTrackerList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54c82649-328e-4d9c-acf2-b9472a81d20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/performance/viewEmployeePerformanceTrackerList</value>
      <webElementGuid>8fc7ae11-b1a5-4768-b922-828c3cb588a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_performance_viewEmployeePerformanceTrackerList</value>
      <webElementGuid>3d2351f5-5275-4ad6-8cf6-1a6a50f99be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee Trackers</value>
      <webElementGuid>6b6432d3-ecc3-4367-836c-7e3ce6c5225b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_performance_viewEmployeePerformanceTrackerList&quot;)</value>
      <webElementGuid>3ae1e42b-2ca7-4e5a-85d4-0ae12294fcf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_performance_viewEmployeePerformanceTrackerList']</value>
      <webElementGuid>4c0237d9-682d-4d99-97f5-7f7d5a0dc4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[4]/ul/li[3]/a</value>
      <webElementGuid>bbff1988-f205-466d-b21a-cf208fb0c9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Employee Trackers')]</value>
      <webElementGuid>8aa6f253-62a8-4afa-88b9-713b83b1fb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Trackers'])[1]/following::a[1]</value>
      <webElementGuid>b784178d-6dce-44b4-b7c6-fd0ffab7e4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review List'])[1]/following::a[2]</value>
      <webElementGuid>134a048e-617a-4b91-aee4-0093ddff17a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::a[1]</value>
      <webElementGuid>d15122fd-a3e3-4d7e-b460-8a63dba5e5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Directory'])[1]/preceding::a[2]</value>
      <webElementGuid>671a5e97-fac0-4712-ad84-cc6d7d33c5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employee Trackers']/parent::*</value>
      <webElementGuid>f16a6571-3fa7-408a-895f-eab210a977c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/performance/viewEmployeePerformanceTrackerList')]</value>
      <webElementGuid>aaf614cf-9d7e-403e-a544-c2e0f66bc7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[3]/a</value>
      <webElementGuid>b19a18e1-fe4b-439f-9eba-a373758d367c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/performance/viewEmployeePerformanceTrackerList' and @id = 'menu_performance_viewEmployeePerformanceTrackerList' and (text() = 'Employee Trackers' or . = 'Employee Trackers')]</value>
      <webElementGuid>7de2c18a-a350-4616-a73c-35d69d24f0ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
