<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Leave Entitlements and Usage Report</name>
   <tag></tag>
   <elementGuidId>78875510-f2d3-4e03-ab95-b90d03b83cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_leave_viewMyLeaveBalanceReport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_leave_viewMyLeaveBalanceReport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6688a4cf-de82-428a-9bec-3c12869ce1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/leave/viewMyLeaveBalanceReport</value>
      <webElementGuid>38b107b1-0974-4dd7-bd36-b7c5cab0bb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_leave_viewMyLeaveBalanceReport</value>
      <webElementGuid>bf2f22b4-555b-4a69-904d-577ae2f37d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Leave Entitlements and Usage Report</value>
      <webElementGuid>80cad00d-1e59-4a74-9463-2352a1aab76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_leave_viewMyLeaveBalanceReport&quot;)</value>
      <webElementGuid>8f93b73e-bc71-4da3-bd64-38d15b7e6177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_leave_viewMyLeaveBalanceReport']</value>
      <webElementGuid>380c33f8-86d0-47f5-9c13-ab8c7034956e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li/ul/li[4]/ul/li/a</value>
      <webElementGuid>dedcceb4-6ac6-44e0-8698-9e9eee65a4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Leave Entitlements and Usage Report')]</value>
      <webElementGuid>1e929b70-5ca8-4a4d-870b-de3aebe3f457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Entitlements'])[1]/following::a[2]</value>
      <webElementGuid>816aef41-80ec-4b50-bab8-c7397b30c8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[1]/following::a[4]</value>
      <webElementGuid>fc6bcff9-1174-4f78-aec5-11326455afb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/preceding::a[1]</value>
      <webElementGuid>c72969f9-6842-45be-8972-bc4d52481842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheets'])[1]/preceding::a[3]</value>
      <webElementGuid>2cff3404-d1ec-4931-8651-b2cacaa8d9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Leave Entitlements and Usage Report']/parent::*</value>
      <webElementGuid>5de294b1-373a-48bb-aad2-71a2507b627d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/leave/viewMyLeaveBalanceReport')]</value>
      <webElementGuid>760697e6-7e7a-4b47-923e-fa34186ff9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/ul/li/a</value>
      <webElementGuid>cc11c128-07ad-4ae8-922d-d0de6ed251a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/leave/viewMyLeaveBalanceReport' and @id = 'menu_leave_viewMyLeaveBalanceReport' and (text() = 'My Leave Entitlements and Usage Report' or . = 'My Leave Entitlements and Usage Report')]</value>
      <webElementGuid>8b79b5f9-2cd1-46e7-b56f-8f2e6a733525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
