<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_From_ui-datepicker-trigger</name>
   <tag></tag>
   <elementGuidId>5b9ce098-0231-472e-9d83-16e064a6c4c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ui-datepicker-trigger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmFilterLeave']/fieldset/ol/li/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0b8ebaf7-8a19-433a-854d-6bb6b0524190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>36269f7a-4956-4096-bc0a-897972103a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_625505b4d6d5f1.18812754/themes/default/images/calendar.png</value>
      <webElementGuid>beec67ac-0917-4112-8ea2-dbb7722e664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmFilterLeave&quot;)/fieldset[1]/ol[1]/li[1]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>6383ab2f-09b5-4207-93d7-e35687ef9d56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmFilterLeave']/fieldset/ol/li/img</value>
      <webElementGuid>69498717-0ff4-4d4f-a062-95ab9a35a1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
      <webElementGuid>9ea4a311-73d1-4b20-a538-c0109a29858d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webres_625505b4d6d5f1.18812754/themes/default/images/calendar.png']</value>
      <webElementGuid>2253c0d4-546e-429a-962c-c030bf572a21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
