<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_HR Manager_shareViewMore_22</name>
   <tag></tag>
   <elementGuidId>2149d661-a07e-454f-85b1-6fe72bb286c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shareViewMore_22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='shareViewMore_22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>542ef02f-df52-4ab4-ba8e-0ab5e3ffac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>viewMoreShare</value>
      <webElementGuid>fb6d75c4-d731-43cc-a426-185445c31b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_625505b4d6d5f1.18812754/orangehrmBuzzPlugin/images/icons/readmore-icon.png</value>
      <webElementGuid>1ce1ea22-49e8-4dd6-a265-53d2d33af3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0dc34bde-1f3d-4adf-a6ff-7e9776117798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shareViewMore_22</value>
      <webElementGuid>4b38e6d3-d980-442d-9da5-2255e90e83d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>1df06ac9-59dd-40e9-8d3f-2068f0b00bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3d7f8303-8bb6-45d7-ad31-5ac9015f1f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shareViewMore_22&quot;)</value>
      <webElementGuid>89683fd1-0311-4ba4-a13b-84083077740f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='shareViewMore_22']</value>
      <webElementGuid>b766f691-50ae-41ea-8f5a-f7fc1e7b58eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='postBodyViewMore']/a/img</value>
      <webElementGuid>01091636-b535-45ca-822a-119670385a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>d7cee7ce-1512-4032-aab4-9d3056416acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webres_625505b4d6d5f1.18812754/orangehrmBuzzPlugin/images/icons/readmore-icon.png' and @id = 'shareViewMore_22']</value>
      <webElementGuid>984add05-b725-451f-b294-7133491f978a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
