<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select a Day to Create Timesheet_addT_e4e8c1</name>
   <tag></tag>
   <elementGuidId>58b0d7e0-478e-4575-8e76-ce62789c2e8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addTimesheetBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addTimesheetBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d73c00d6-f408-4c26-8507-01c82d5bdf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c263db0-e75c-4777-9caf-71926a107981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addTimesheetBtn</value>
      <webElementGuid>6228163b-1d31-44a4-9fa6-4cdd7f0409fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>2a76bc07-06fb-4754-ba79-b544aef50788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>051aca7a-b057-4a7e-b9ec-8a6c86bab102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>11a92146-c101-45a1-acdf-ad296f2dab98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTimesheetBtn&quot;)</value>
      <webElementGuid>cb35a672-aa68-4539-ad7e-475f65ab5c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addTimesheetBtn']</value>
      <webElementGuid>1c34e22b-879a-4ff5-90a5-dd6422498864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='createTimesheet']/div[3]/input</value>
      <webElementGuid>f2aa8d5c-98a9-4837-a906-285e9d7a0181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>4da5c549-55d9-4729-ad06-37f87e35ba68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'addTimesheetBtn']</value>
      <webElementGuid>c8809fb7-54fc-4fb0-8401-01bd4c5d60fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
