<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GPAScore_educationgpa</name>
   <tag></tag>
   <elementGuidId>eb9eb334-3072-4b55-805f-24263600e29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#education_gpa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='education_gpa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86c3e700-d901-4e69-b98a-4e26cbce6866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>019002b2-fb2e-42f9-b4bc-d49d0bcc8d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>education[gpa]</value>
      <webElementGuid>b68b51fa-efc2-478f-936d-0130a7d6a119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>e19997ce-6509-4051-9916-dbd9503e5e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>5442136f-a25b-4aaa-88df-6aec58644836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>education_gpa</value>
      <webElementGuid>f32a6d72-d5e0-4fa9-9301-d5716760e974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;education_gpa&quot;)</value>
      <webElementGuid>bd4df75c-3726-4f7a-83d6-9b0a94af4be7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='education_gpa']</value>
      <webElementGuid>ff434eae-55cb-480e-9147-5c946f88047f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEducation']/fieldset/ol/li[5]/input</value>
      <webElementGuid>2eb65f0e-f837-46e8-95f1-5510c1f59891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>bae8795f-19df-4733-87fe-c7c6f4bd89d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'education[gpa]' and @id = 'education_gpa']</value>
      <webElementGuid>ab6ccd71-0dc0-4ff3-9f14-3cafaff82c74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
