<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Apply Leave</name>
   <tag></tag>
   <elementGuidId>ae89a5a6-7c66-4847-9b83-ed49b8b68892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.quickLinkText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard-quick-launch-panel-menu_holder']/table/tbody/tr/td/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a34c9770-eef1-427a-a2e6-6de28301c0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quickLinkText</value>
      <webElementGuid>c47df233-8483-4bfd-ad17-cf926fcdc0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply Leave</value>
      <webElementGuid>01938d4c-85dd-4697-9d1a-a120e5cc0fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-quick-launch-panel-menu_holder&quot;)/table[@class=&quot;quickLaungeContainer&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;quickLaunge&quot;]/a[1]/span[@class=&quot;quickLinkText&quot;]</value>
      <webElementGuid>116e165a-72f1-41bf-ad9c-e2eac16a7e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-quick-launch-panel-menu_holder']/table/tbody/tr/td/div/a/span</value>
      <webElementGuid>33a553f3-9572-464a-9366-35a0cbabf3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Launch'])[1]/following::span[1]</value>
      <webElementGuid>a2b569c8-e601-4daf-9981-d5f658cd53ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[1]</value>
      <webElementGuid>f883c884-64b0-4998-9e40-3cf8fe74e8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[2]/preceding::span[1]</value>
      <webElementGuid>6488cc3b-897c-465b-a973-d1038c5c903b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheet'])[1]/preceding::span[2]</value>
      <webElementGuid>b74b8430-7fee-47c9-850d-016fd3d01af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply Leave']/parent::*</value>
      <webElementGuid>f1ec7ee3-19d0-403d-91ad-858508e5ebb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a/span</value>
      <webElementGuid>4336a2f6-f843-4b87-86e8-e7e5918f18dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Apply Leave' or . = 'Apply Leave')]</value>
      <webElementGuid>3b76cb96-ff75-4f81-9524-37571a62157c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
