<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Attendance</name>
   <tag></tag>
   <elementGuidId>b7a5f5db-77cc-47b7-92e5-63316dc6908d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_attendance_Attendance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_attendance_Attendance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f4c33a3-f515-47b8-842f-8d4e0abde291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>fa98eaff-b72a-4546-9a3f-a7961e37f87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_attendance_Attendance</value>
      <webElementGuid>24e9a62f-f464-4160-bcd3-99fc804a57c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>0977498e-b3dd-4734-adc9-224c6aae5bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attendance</value>
      <webElementGuid>3a5e7658-a668-44f9-a7ae-0af15d2b8d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_attendance_Attendance&quot;)</value>
      <webElementGuid>15087d40-8719-4573-8ec6-a03fc7dd9466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_attendance_Attendance']</value>
      <webElementGuid>91037f89-f2f8-4ba2-a55e-aff2f5c055d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[4]/ul/li[2]/a</value>
      <webElementGuid>01804c9d-4956-4efb-ba91-c11091e8c028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Attendance')]</value>
      <webElementGuid>8069718b-f868-47fc-9666-dc5ff903a6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Timesheets'])[1]/following::a[1]</value>
      <webElementGuid>553280bb-8d5d-4227-b42a-bc0b616d4cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheets'])[1]/following::a[2]</value>
      <webElementGuid>8cb6faa8-cc1a-42e7-bc51-3591fc630e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Records'])[1]/preceding::a[1]</value>
      <webElementGuid>9a9d320f-3e6f-4b34-9639-358008f3e132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punch In/Out'])[1]/preceding::a[2]</value>
      <webElementGuid>398eac76-25c0-4172-934a-cd8f532e9acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attendance']/parent::*</value>
      <webElementGuid>06d1f912-29b8-4de8-908c-f2fa1635f99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>5f8fd19b-f80d-44e0-9be3-cccb680688ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>9706c85b-59c6-495b-a76b-b31f71bd99f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'menu_attendance_Attendance' and (text() = 'Attendance' or . = 'Attendance')]</value>
      <webElementGuid>53d0ffc5-4a9c-4fb7-a077-4fac640c972d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
