<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_20</name>
   <tag></tag>
   <elementGuidId>aa0b2ed8-654c-49f1-931f-abcc3979be4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ui-state-default.ui-state-highlight.ui-state-active.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-datepicker-div']/table/tbody/tr[4]/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec51cd19-0773-4209-988a-723d39274046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-state-default ui-state-highlight ui-state-active ui-state-hover</value>
      <webElementGuid>669b638a-9f4e-4e4b-8ec2-9e5db1a9559f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>15f06df4-7da3-469b-b95e-de462ea71fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0ca1ae60-8870-4937-9e1c-05ccbb61c18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-datepicker-div&quot;)/table[@class=&quot;ui-datepicker-calendar&quot;]/tbody[1]/tr[4]/td[@class=&quot;ui-datepicker-days-cell-over ui-state-fullday ui-datepicker-current-day ui-datepicker-today&quot;]/a[@class=&quot;ui-state-default ui-state-highlight ui-state-active ui-state-hover&quot;]</value>
      <webElementGuid>9501be65-0844-41b6-a151-e43975174a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-datepicker-div']/table/tbody/tr[4]/td[3]/a</value>
      <webElementGuid>6f813069-2645-40f3-8dbd-fc09189556b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'20')]</value>
      <webElementGuid>b97ce913-07f4-459a-a736-d3c02674be87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::a[20]</value>
      <webElementGuid>944947ec-74b3-4863-8b77-5c7ca811f011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::a[20]</value>
      <webElementGuid>b27de9fb-5ff5-4bd7-95b5-73a0e2d937d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20']/parent::*</value>
      <webElementGuid>9f8e01b8-43a1-4ea2-867a-a19671b0006e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[39]</value>
      <webElementGuid>625a47fa-5d11-442f-8239-41372928a8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/a</value>
      <webElementGuid>24b10ec3-5758-4920-b8dc-c0715124feac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '20' or . = '20')]</value>
      <webElementGuid>09c6c40a-8e2b-49ca-8c1b-777c3c31bbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
