<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Time</name>
   <tag></tag>
   <elementGuidId>0b75c551-17ac-44a4-970b-6e19530dc371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_time_viewTimeModule > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_time_viewTimeModule']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>03c46403-b4cc-4158-b2ac-8691c54eb1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time</value>
      <webElementGuid>7cd6a265-9e75-4119-9183-4630cfc731f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_time_viewTimeModule&quot;)/b[1]</value>
      <webElementGuid>85038871-2661-4efc-9085-a19c13284491</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_time_viewTimeModule']/b</value>
      <webElementGuid>261fd619-03c3-4b35-83f0-d80777bf6425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Leave'])[1]/following::b[1]</value>
      <webElementGuid>60676f6b-8526-4d06-869d-7438c2f27462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave List'])[1]/following::b[1]</value>
      <webElementGuid>89771325-7336-47b7-99b5-27d0e3b93ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheets'])[1]/preceding::b[1]</value>
      <webElementGuid>590333b1-f6f3-4b88-a6c2-cb38794e5a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Timesheets'])[1]/preceding::b[1]</value>
      <webElementGuid>6384cabe-c3cf-4b46-ada2-db36d85f78df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Time']/parent::*</value>
      <webElementGuid>9513fd0d-5151-494a-b3ff-099eb4a7f002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/b</value>
      <webElementGuid>3673910a-b3cd-4db3-aef7-6d6dfc836dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Time' or . = 'Time')]</value>
      <webElementGuid>99cfad9f-6774-480b-a13e-ddae5b062655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
