<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Date_ui-datepicker-trigger</name>
   <tag></tag>
   <elementGuidId>ee08406b-e966-4512-9c2e-349f0752e45c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ui-datepicker-trigger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='reportForm']/fieldset/ol/li/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4458c6d7-e382-4f7b-a02e-bc871209505a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>6a1cf719-78b0-4146-9db0-f2231794c3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_625f21a4526f61.48895373/themes/default/images/calendar.png</value>
      <webElementGuid>9fb84f46-b13e-43d5-b31b-c00e20ee4013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportForm&quot;)/fieldset[1]/ol[@class=&quot;normal&quot;]/li[1]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>a24b907f-fac8-40c7-83bb-903ac97497ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='reportForm']/fieldset/ol/li/img</value>
      <webElementGuid>7e68dc98-afa9-4ed2-91c1-92278c56cb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
      <webElementGuid>26229ad7-e6c3-4851-a972-e4f4fd61a2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webres_625f21a4526f61.48895373/themes/default/images/calendar.png']</value>
      <webElementGuid>c8a6fe7d-b1ad-4998-8a1d-631203c33019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
