<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOGIN Panel_txtUsername</name>
   <tag></tag>
   <elementGuidId>a47ad05e-60d2-48f5-a3d2-69ad1f7399e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUsername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUsername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5cbe264-a74b-4631-86c7-7844e7317118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>6b856293-c5bb-4988-a29e-422e82d50f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>8fa4e9ea-7fe0-4664-a105-c4a2b0ec9fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3517d8b8-7b0a-47e6-a10d-62c4d788d842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUsername&quot;)</value>
      <webElementGuid>74484ea4-650d-46fe-be95-bb1ff10b7f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUsername']</value>
      <webElementGuid>050026ea-3aa7-4c5b-ba41-5852993601bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divUsername']/input</value>
      <webElementGuid>2ecadf40-8da6-4ebe-a67c-a1891433fc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8626f9a6-bb55-4870-b279-716424a87a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtUsername' and @id = 'txtUsername' and @type = 'text']</value>
      <webElementGuid>fc41e72b-9f8d-4dd6-a166-f926d36277b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
