<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_organizationphone</name>
   <tag></tag>
   <elementGuidId>98002852-187a-48c6-9ff3-6a6e52cfcb8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#organization_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b650f15-c1fd-4564-887d-0f3939877514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>073d22e9-77ba-403a-b336-43155cef3205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization[phone]</value>
      <webElementGuid>a349209d-e653-4bd7-b982-cd91dd329368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0123334567</value>
      <webElementGuid>243b2d05-181a-4197-b4d2-627d64658dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>299c4934-ccb1-4826-9ea9-0631776eb3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization_phone</value>
      <webElementGuid>9722143d-2a45-484d-89a3-362a2751bf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization_phone&quot;)</value>
      <webElementGuid>f2db8530-1d2a-4403-adad-ffab0ca7611d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization_phone']</value>
      <webElementGuid>14f6e253-f895-4490-9ef1-3c072139e9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmGenInfo']/fieldset/ol[2]/li/input</value>
      <webElementGuid>ec79aa76-103f-4e31-958e-094de388e40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[2]/li/input</value>
      <webElementGuid>717eae84-8f5d-40c2-8b6a-4aee41e2d53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'organization[phone]' and @id = 'organization_phone']</value>
      <webElementGuid>33613309-fc3b-4f91-bb05-5a2a8b0ff152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
