<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StateProvince_organizationprovince</name>
   <tag></tag>
   <elementGuidId>b8c5918c-ac6c-4e9c-951f-ddeb51ed7247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organization_province']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#organization_province</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>513230d8-5437-4d96-8241-4e77f3ffb43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e45b3c17-9982-47f9-84fc-b67937c7d0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization[province]</value>
      <webElementGuid>cffbce58-cd1b-4e59-9ae2-868062d69fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NJ</value>
      <webElementGuid>ba05905c-0fc4-423a-85d0-036227b6d86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a3314d4a-a3a0-4a8e-bb7c-36b576b6f815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organization_province</value>
      <webElementGuid>89f289e4-fa4b-406a-b1cb-362e5c4100d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization_province&quot;)</value>
      <webElementGuid>0a5e954a-c791-4123-9e75-2b272c6b61e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organization_province']</value>
      <webElementGuid>1f83d73e-6314-4779-af91-2db5326f194b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmGenInfo']/fieldset/ol[3]/li[4]/input</value>
      <webElementGuid>1be83195-37c3-43ba-b4d9-119124e52a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol[3]/li[4]/input</value>
      <webElementGuid>a9f8254d-9053-450d-a19d-a5530283867b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'organization[province]' and @id = 'organization_province']</value>
      <webElementGuid>1994b1a7-567c-4cb3-a5c0-ee1e2d74dccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
