<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location__search</name>
   <tag></tag>
   <elementGuidId>c120721b-a640-43af-b076-11284bf94b1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b85b43e8-bb53-49aa-b5ef-e5209d3a0de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>39b2a9bf-af0e-46be-b26e-8bbb1b2fc550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchBtn</value>
      <webElementGuid>33a672f6-1124-46ce-a9aa-59a3cf0379b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f6cb06fc-e5b5-4b91-bfb1-cb9fd7b25ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_search</value>
      <webElementGuid>9f85ac71-8924-464e-9ee5-b05843a685bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>4807bc1e-4575-4843-abf8-bde20d1ec225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBtn&quot;)</value>
      <webElementGuid>fbeee763-aa81-4008-868a-d7357761a316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchBtn']</value>
      <webElementGuid>47ca2667-a787-4c69-86b1-eecc4a5739c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/p/input</value>
      <webElementGuid>bdf7624f-7926-44e3-9f50-2eb36a5314cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>fa6b0ff3-17ee-49cc-a06d-152615d6ed5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'searchBtn' and @name = '_search']</value>
      <webElementGuid>2e927dc3-6e04-4c81-9868-fac5df6090eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
