<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vacancies</name>
   <tag></tag>
   <elementGuidId>df5e2b51-5aab-4866-b755-dfd709989025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_recruitment_viewJobVacancy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_recruitment_viewJobVacancy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>498b1539-aeaa-4bbf-8fba-76a2dbe7f7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/recruitment/viewJobVacancy</value>
      <webElementGuid>2dd5e435-5f13-4bdd-8ff8-babec5f2ba99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_recruitment_viewJobVacancy</value>
      <webElementGuid>0d3af064-cc22-4a47-b539-4347cf19a55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vacancies</value>
      <webElementGuid>90add15f-9f31-41db-8688-b475c6f05416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_recruitment_viewJobVacancy&quot;)</value>
      <webElementGuid>c8e3dd0b-0aa6-4d8b-ae4b-8765ee04d958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_recruitment_viewJobVacancy']</value>
      <webElementGuid>f9e70225-2876-455a-8090-ba322990720a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[5]/ul/li[2]/a</value>
      <webElementGuid>a934a96c-bba8-46da-bda1-ce19e0636d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vacancies')]</value>
      <webElementGuid>a8a28755-59ab-4952-aa43-dbd53473b343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidates'])[1]/following::a[1]</value>
      <webElementGuid>e9c8bdd5-643c-4860-bc4c-f9b17a24189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment'])[1]/following::a[2]</value>
      <webElementGuid>a012a885-b870-45fa-852e-f06fbe439bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Info'])[1]/preceding::a[1]</value>
      <webElementGuid>a00daa0e-32fb-421c-9e08-c04ebd0f19b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance'])[1]/preceding::a[2]</value>
      <webElementGuid>7ea5ca55-0a87-4420-aa9c-8f5a0efbb949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vacancies']/parent::*</value>
      <webElementGuid>d81332e4-41d6-4705-8396-4258e98b9fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/recruitment/viewJobVacancy')]</value>
      <webElementGuid>0fded145-3d3c-4a1d-b445-9ca4ca16d89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[2]/a</value>
      <webElementGuid>ebf4c82b-49ad-417a-93c8-80d13706adfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/recruitment/viewJobVacancy' and @id = 'menu_recruitment_viewJobVacancy' and (text() = 'Vacancies' or . = 'Vacancies')]</value>
      <webElementGuid>7b5ecca7-cc1b-44a5-9820-c326c60d60da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
