<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of Positions_addJobVacancynoOf_9b2c22</name>
   <tag></tag>
   <elementGuidId>a375bba8-690b-44da-b418-646b86c98962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addJobVacancy_noOfPositions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addJobVacancy_noOfPositions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5cf01b2b-6879-417a-b9e2-be99f1a59f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f675d15a-585f-4f81-b319-d9ced1ce8f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addJobVacancy[noOfPositions]</value>
      <webElementGuid>eaf79066-eb4d-4535-843b-ec883f538e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ddecdc37-0b96-480b-a6b1-21f3f7a958db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addJobVacancy_noOfPositions</value>
      <webElementGuid>4e3439ab-5926-4273-8653-7aaad24c1307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addJobVacancy_noOfPositions&quot;)</value>
      <webElementGuid>ea23f344-a646-4e28-8fbe-41dabbbbd967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addJobVacancy_noOfPositions']</value>
      <webElementGuid>f49c7ee5-e3b0-401e-b0bc-510702e3d533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddJobVacancy']/fieldset/ol/li[4]/input</value>
      <webElementGuid>98eb1be5-b019-42db-8f7f-4d1c343ee9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/input</value>
      <webElementGuid>19e967a3-14b0-4d61-b0e7-62e835d721bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addJobVacancy[noOfPositions]' and @id = 'addJobVacancy_noOfPositions']</value>
      <webElementGuid>bb95e78d-4614-4321-a3b9-880b58f235d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
