<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_addJobVacancydescription</name>
   <tag></tag>
   <elementGuidId>7a21cfd4-ca89-416f-ba29-23a35d2f6ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addJobVacancy_description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='addJobVacancy_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>10ab42e9-4262-4702-9882-0fb53e365b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>5dfeeae6-990f-4ab9-84da-0782453422dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>863383e7-8b19-4f9a-9518-23a142119dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addJobVacancy[description]</value>
      <webElementGuid>6c9c8048-5e1f-48e9-a15c-2ab2157e36cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addJobVacancy_description</value>
      <webElementGuid>bb1aad4a-19fe-4f4b-995a-821ef6f5f5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addJobVacancy_description&quot;)</value>
      <webElementGuid>7bd24a56-4c03-43a9-ac9c-98ccd8f1d44a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='addJobVacancy_description']</value>
      <webElementGuid>9929b9c6-2388-4678-af6a-746bdd0592d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddJobVacancy']/fieldset/ol/li[5]/textarea</value>
      <webElementGuid>02877575-5d0a-4c8c-88af-50778c517072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>83fc7703-f326-4feb-9eab-83da14e01932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'addJobVacancy[description]' and @id = 'addJobVacancy_description']</value>
      <webElementGuid>b687b830-00cf-4564-bc6c-bd9c2730471d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
