<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KPIs</name>
   <tag></tag>
   <elementGuidId>e6d745ba-13d7-455c-a3d0-f446af671d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_performance_searchKpi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_performance_searchKpi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14f581f4-6433-4c58-b587-17f1b51ac8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/performance/searchKpi</value>
      <webElementGuid>37185ef1-e75e-48e3-a3d3-814419658362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_performance_searchKpi</value>
      <webElementGuid>44705e5e-5cd0-4be9-864e-fae41e4f26a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KPIs</value>
      <webElementGuid>7aa4be6a-0555-4b16-b583-23a9a357dd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_performance_searchKpi&quot;)</value>
      <webElementGuid>8ca424e9-fb4f-4146-a87a-7f62903c2f54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_performance_searchKpi']</value>
      <webElementGuid>741e628d-9ac2-46e0-b52e-c34345a39eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[7]/ul/li/ul/li/a</value>
      <webElementGuid>807cb932-912b-47ae-bdc8-ab1cba7c5570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'KPIs')]</value>
      <webElementGuid>6f2abea7-8994-446f-af1f-ed64b97d3e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance'])[1]/following::a[2]</value>
      <webElementGuid>199f4102-77b0-48ea-ae82-491e13b385ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Info'])[1]/following::a[3]</value>
      <webElementGuid>f42b1756-69ad-4a22-bc2f-643f20430911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trackers'])[1]/preceding::a[1]</value>
      <webElementGuid>ea1cd156-4944-4d5b-a558-77d6af4db031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Reviews'])[2]/preceding::a[3]</value>
      <webElementGuid>46f6057b-5df2-4601-9a31-9055bae172a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KPIs']/parent::*</value>
      <webElementGuid>ae87f41a-4f43-42ed-aa71-c1b455720821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/performance/searchKpi')]</value>
      <webElementGuid>a15007ab-98de-47f5-a838-a3dad1a00eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/ul/li/a</value>
      <webElementGuid>126d2a2b-50c5-4a5a-8018-3f7ae700f21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/performance/searchKpi' and @id = 'menu_performance_searchKpi' and (text() = 'KPIs' or . = 'KPIs')]</value>
      <webElementGuid>122288a0-9d19-4230-86b9-0e220ea20af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
