<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hide Options_modal-backdrop in</name>
   <tag></tag>
   <elementGuidId>00c519a6-ece2-4496-80a0-eb91b0977638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-backdrop.in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3e47226-f0b9-4212-9de0-c3a6f03f88b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-backdrop in</value>
      <webElementGuid>158d94e4-9fab-400e-a0a8-fb11ca9fac48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal-backdrop in&quot;]</value>
      <webElementGuid>f1b83239-6de1-45ec-8000-403df376912c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>e2394e50-b312-4010-bedb-9f75a206d0a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
