<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__addJobVacancyhiringManager</name>
   <tag></tag>
   <elementGuidId>fc7cd700-f87c-44af-85e2-40d1fe6dfe04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addJobVacancy_hiringManager']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addJobVacancy_hiringManager</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a2c78f1-f40b-42fd-a582-25aaf9472f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af067c97-597a-46b9-ada0-98add209fd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addJobVacancy[hiringManager]</value>
      <webElementGuid>51472011-ae38-44e2-9fec-f4421933f47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e987f563-d0b7-4d13-8b98-3b5817bd9a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addJobVacancy_hiringManager</value>
      <webElementGuid>102ebf4e-35ad-45c6-99b1-b184cb862a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c65e71b9-30fb-41ab-b506-c5f1c9c5f977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>9198f097-fd54-4a63-a44a-859b72328761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addJobVacancy_hiringManager&quot;)</value>
      <webElementGuid>401886eb-0aec-46e8-9ff8-97a1db4c4608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addJobVacancy_hiringManager']</value>
      <webElementGuid>2d39ff14-8e1d-4ec3-bb97-497d9625e2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddJobVacancy']/fieldset/ol/li[3]/input</value>
      <webElementGuid>e5628d2e-9f6f-4c73-9c98-8513477c0457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>aec7ecd4-f1c9-4734-9019-6028e8d6cb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addJobVacancy[hiringManager]' and @id = 'addJobVacancy_hiringManager']</value>
      <webElementGuid>75ac405e-dff2-4fd4-ab22-67c80731f9a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
