<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrangeHRM - Confirmation Required_dia_9fc7db</name>
   <tag></tag>
   <elementGuidId>1a3600bd-215d-46e3-968f-d87fd72006a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dialogDeleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dialogDeleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5249598-9b31-4ca5-ace5-f548bbd74d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5234de7c-b2c8-4d00-8fd6-14558bf5dc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn hover</value>
      <webElementGuid>5c76fea7-83ce-4ad2-88c4-f42c05970542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>df9209f2-040a-4048-8159-31be12742ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialogDeleteBtn</value>
      <webElementGuid>216701be-b442-4868-879b-f209ca880d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>7a3b9479-695e-42bf-87e9-108c110a695a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogDeleteBtn&quot;)</value>
      <webElementGuid>5cb4ed80-7a69-4ae5-bd57-4c864148bf1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dialogDeleteBtn']</value>
      <webElementGuid>9de265ff-1da9-40c3-ba1d-f8ed82771d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteConfirmation']/div[3]/input</value>
      <webElementGuid>369f7be2-f5bf-4dc7-ba4d-1fd070251a16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>68ec270d-7745-4652-9a7a-15f225aa1b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'dialogDeleteBtn']</value>
      <webElementGuid>d8daa79b-8190-490f-bdca-fc7ba3390965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
