<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_x</name>
   <tag></tag>
   <elementGuidId>29ca2adf-33cd-4505-a407-dceee33ad50f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='treeLink_delete_15']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#treeLink_delete_15</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14481742-6986-427e-b581-d3a7fc62bff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?</value>
      <webElementGuid>4b911a6e-9957-4045-b0a7-d94ee8f2c62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>treeLink_delete_15</value>
      <webElementGuid>2761c5ff-f6d5-45da-be61-34cd09af511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>deleteButton</value>
      <webElementGuid>70fac8a8-ee3d-4f37-a9bb-91512cca497a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> x</value>
      <webElementGuid>9f913c31-8929-4987-8dea-870b8622e435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeLink_delete_15&quot;)</value>
      <webElementGuid>3a8fa3e9-a2bd-4a49-a6e4-037237a0cf9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='treeLink_delete_15']</value>
      <webElementGuid>b0e23da7-7e3f-46fb-915c-ad54a18320d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='node_15']/a[3]</value>
      <webElementGuid>0cf1d8a2-be60-4eae-a5d0-efe49105975d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'x')])[13]</value>
      <webElementGuid>705fe904-01ee-40f1-8604-f997c8a697b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[14]/following::a[1]</value>
      <webElementGuid>067c91fa-c10f-46d7-aa80-2881810361ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Management'])[2]/following::a[2]</value>
      <webElementGuid>eaf4ef60-1fd1-4c5c-8e90-f94e065452a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[1]</value>
      <webElementGuid>d31ca229-6622-42b9-94f3-22844b9f53df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM - Edit Unit'])[1]/preceding::a[2]</value>
      <webElementGuid>c0ae1bd0-01eb-4dd7-9987-a9aeecb842d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#?')])[41]</value>
      <webElementGuid>19cdb6cb-c85a-41cc-9c71-3df403af6783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a[3]</value>
      <webElementGuid>7d345fe2-7751-4451-902e-8a2b74f44de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?' and @id = 'treeLink_delete_15' and (text() = ' x' or . = ' x')]</value>
      <webElementGuid>abe760a4-d63f-4e0b-bfb7-9610bdc4fd93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
