<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtName</name>
   <tag></tag>
   <elementGuidId>0b801172-4437-4d71-9f12-ad4b5011ee8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1acfc061-9bdf-4603-9c2c-aa3ea06da264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6134f19-b8c5-4c07-b1e7-20ddf3e14eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtName</value>
      <webElementGuid>e3173b09-e7d7-4626-8397-737632c90190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText validation-error</value>
      <webElementGuid>7b0fcdbf-8a79-4887-9af6-bb76ecbb8c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtName</value>
      <webElementGuid>28623b0a-37f3-483c-9f6c-3c5fa1f7803f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtName&quot;)</value>
      <webElementGuid>c1b3894b-1957-4c35-a60c-a8134c7f0bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtName']</value>
      <webElementGuid>362e0bbc-cf93-47f2-b0a5-0f00f3b1de1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ohrmFormComponent_Form']/fieldset/ol/li[2]/input</value>
      <webElementGuid>6b3eaa64-2244-45fa-914e-f6f2b87dd88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>2b6af29d-2e0c-40da-8d74-fca5f586f14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtName' and @id = 'txtName']</value>
      <webElementGuid>e4162de2-2f86-45bc-9964-6d38764cbc30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
