<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OrangeHRM</name>
   <tag></tag>
   <elementGuidId>4c2d0465-e340-4031-aa89-911a8fb3b461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#span_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9e7c8eba-4616-49e9-88ce-081fdbff2017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>span_1</value>
      <webElementGuid>36ca7293-a4ca-48ed-858b-c7c1d3fc5595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>labelNode</value>
      <webElementGuid>3a8b26fa-d927-4a97-9f75-b53b5f84a171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OrangeHRM</value>
      <webElementGuid>2bda9816-b55e-4116-9787-4be1601bfac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_1&quot;)</value>
      <webElementGuid>c5d3035c-0e76-4769-a7a7-f647aade9b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='span_1']</value>
      <webElementGuid>0c1ab70d-2e1c-4eab-a985-ec80b5ac9b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='node_1']/span</value>
      <webElementGuid>7fe23d86-fb12-4858-a8f9-37589ecb7989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Structure'])[1]/following::span[1]</value>
      <webElementGuid>c9c0bcf1-ee43-44dd-bb53-36837016162a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buzz'])[1]/following::span[1]</value>
      <webElementGuid>f8a0cb75-fc2f-4540-9291-11b5c63b9316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM'])[3]/preceding::span[1]</value>
      <webElementGuid>6bcf2805-e860-4ab7-8e08-8b9b8df96a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::span[1]</value>
      <webElementGuid>b4c65039-78d0-482f-9f9c-2ea46002ed02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>07701d0c-e1ff-44ad-8218-0937cfe47a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'span_1' and (text() = 'OrangeHRM' or . = 'OrangeHRM')]</value>
      <webElementGuid>333e7815-6909-42e1-8605-4d30ee9fb9ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
