<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Senior QA Lead</name>
   <tag></tag>
   <elementGuidId>56df2a7d-8549-4894-9648-9fd7ac8e7226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultTable']/tbody/tr[6]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81895e83-b4f5-4d76-ae3c-f4c9066f0ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>addJobVacancy?Id=6</value>
      <webElementGuid>eb43f777-4b35-4520-ac4b-170687f6925b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Senior QA Lead</value>
      <webElementGuid>a1e336d6-08d4-4183-93f3-cb445efaca2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultTable&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;left&quot;]/a[1]</value>
      <webElementGuid>ad7a6f86-fb20-45a8-9830-26e9b66b7016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[6]/td[2]/a</value>
      <webElementGuid>e828f3d1-9bec-4830-937d-132bc328b8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Senior QA Lead')]</value>
      <webElementGuid>f0adace5-8ab1-43af-b216-20aa83d19783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[6]/following::a[1]</value>
      <webElementGuid>773fe48b-6f34-4d23-ae51-5f0dca490048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linda Jane Anderson'])[2]/following::a[1]</value>
      <webElementGuid>6b8c6557-697b-4d82-aaaf-b2e732795b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA Lead'])[2]/preceding::a[1]</value>
      <webElementGuid>989fbcbe-f15c-4c9a-8a17-41c2dd2aad1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odis Adalwin'])[4]/preceding::a[1]</value>
      <webElementGuid>18eae985-8101-4311-9b10-b9d96bb47917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'addJobVacancy?Id=6')]</value>
      <webElementGuid>9990d2af-ad34-4e43-a52c-ebf0b84589cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/a</value>
      <webElementGuid>009c9f1f-490a-484c-bd4c-589a78ac1df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'addJobVacancy?Id=6' and (text() = 'Senior QA Lead' or . = 'Senior QA Lead')]</value>
      <webElementGuid>daec59b9-3f15-462f-a6e7-07a447ef8253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
