<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__addJobVacancyname</name>
   <tag></tag>
   <elementGuidId>f2e783b1-6238-491a-8f2f-395cbfbfc740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addJobVacancy_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addJobVacancy_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adf483e8-4175-45c3-a502-3232ca5bf21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>335d47f5-5be1-4122-a17b-78d1960eaa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addJobVacancy[name]</value>
      <webElementGuid>50921f58-8afa-4f4e-80d1-c8e15c1a5621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>93d00141-08ad-4350-b7a7-c9444da54e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addJobVacancy_name</value>
      <webElementGuid>7be2d00e-a2f1-4082-8c28-94242e6e8cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addJobVacancy_name&quot;)</value>
      <webElementGuid>799d58d8-a539-44ec-ae45-ff8ce5696495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addJobVacancy_name']</value>
      <webElementGuid>65f593de-9cd6-4764-9389-cf8fbcd15d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddJobVacancy']/fieldset/ol/li[2]/input</value>
      <webElementGuid>9d147255-e802-42d0-8410-bcb68767d92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>22e5ccf7-f90f-4b3a-b99b-93c5954a65b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addJobVacancy[name]' and @id = 'addJobVacancy_name']</value>
      <webElementGuid>7c0755a2-3cba-4930-8b44-286c80a6e8d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
