<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__workShiftname (1)</name>
   <tag></tag>
   <elementGuidId>609db053-dcb9-4297-89c5-81bf178ed628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workShift_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workShift_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4aed97b8-1d92-45bb-b77c-f57d554b7488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>0a2d9ab5-a408-4bb9-8abd-63e87600ad63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>923b0b8a-eb38-4c7e-a809-b7f803a2a847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workShift[name]</value>
      <webElementGuid>a3edc6c9-6c92-44b0-9c7c-4ca3f05a21eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workShift_name</value>
      <webElementGuid>4315c5d7-da0b-4265-ae3d-4447a1cff481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workShift_name&quot;)</value>
      <webElementGuid>46713feb-e8bc-44aa-ac8f-c5bb9060ab05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workShift_name']</value>
      <webElementGuid>723a6c7c-86b4-4564-aa9e-7fe0ccef4fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmWorkShift']/fieldset/ol/li/input</value>
      <webElementGuid>2a4fbd75-2aea-40cb-a03f-02675b4af74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>ea2c2eec-d966-4075-a839-d2aae26c2889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'workShift[name]' and @id = 'workShift_name']</value>
      <webElementGuid>d02a71ce-d98c-414d-a12d-6aabf76a0ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
