<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnSave</name>
   <tag></tag>
   <elementGuidId>594d6940-a803-483e-9f5b-3ba6dfd8d1b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81e9c85d-d0fe-4a6c-97f5-dcc63980f480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e369779-2671-4fdc-9793-060b101aec19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>abe004d2-c24e-4db4-9b6b-3ed80bae31eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSave</value>
      <webElementGuid>6a12421c-ed79-4e2e-aa31-5659d3efaf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSave</value>
      <webElementGuid>f524e1f1-9107-46e3-ab65-81363ff329b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1ac6f353-8ed0-4001-b4a3-01f98905d5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSave&quot;)</value>
      <webElementGuid>a8c6bf01-50d5-4123-bfea-9e223973b573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSave']</value>
      <webElementGuid>a81b47e5-4d4e-4cd7-99f9-62b6b193a4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmWorkShift']/fieldset/p/input</value>
      <webElementGuid>d043607d-58f3-4d30-8d7c-29fa4b434e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>55c60dd9-c749-443e-b938-50746c42e49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSave' and @id = 'btnSave']</value>
      <webElementGuid>a8419e4e-7ad4-4f43-a266-f1e1d1fbef6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
