<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reports</name>
   <tag></tag>
   <elementGuidId>75106dd5-2c3e-465c-bc69-61d6e9a9b031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_core_viewDefinedPredefinedReports</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_core_viewDefinedPredefinedReports']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29cc0b50-12f2-4707-85c5-cff3aea0a64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED</value>
      <webElementGuid>849d1f20-0eae-4b30-b7df-4c5e96bea6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_core_viewDefinedPredefinedReports</value>
      <webElementGuid>99cc8ca7-6bbe-46b9-9f25-f554efb178aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reports</value>
      <webElementGuid>e5c496aa-bcef-48da-bf1f-2db9ff93ef4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_core_viewDefinedPredefinedReports&quot;)</value>
      <webElementGuid>4062038c-b0c0-4f6f-8bb5-f5b7432dff81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_core_viewDefinedPredefinedReports']</value>
      <webElementGuid>d03c90f2-21cb-4a6f-8a24-7de2e91ac937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[2]/ul/li[4]/a</value>
      <webElementGuid>6cc5b61e-ff06-4e47-b9d2-04861d3df1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reports')]</value>
      <webElementGuid>9f6f752c-7ece-4466-85f3-0b01b98bf502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Employee'])[1]/following::a[1]</value>
      <webElementGuid>2b4fd374-98cc-4bd6-9e94-9113358a8b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee List'])[1]/following::a[2]</value>
      <webElementGuid>6ded14dd-aae4-4c43-9ff5-ff1ff7aa9f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>e6de16a1-744f-41fa-9ed9-2d86078c11d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::a[2]</value>
      <webElementGuid>46573c4e-b354-465a-833f-76386c0f0384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reports']/parent::*</value>
      <webElementGuid>1ee5a914-7b7c-45b9-9ebc-db33696d1ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED')]</value>
      <webElementGuid>6cc60163-f581-4b0f-befc-335a3120828d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>4dc2f5d1-1588-43f4-9f81-add1954f8121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/core/viewDefinedPredefinedReports/reportGroup/3/reportType/PIM_DEFINED' and @id = 'menu_core_viewDefinedPredefinedReports' and (text() = 'Reports' or . = 'Reports')]</value>
      <webElementGuid>870e40d6-3806-4bc0-8b2d-eb3b2dae906a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
