<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit Id_txtUnit_Id</name>
   <tag></tag>
   <elementGuidId>d5441dc0-6c41-4406-b967-dba9055d3507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUnit_Id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtUnit_Id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>102125de-74a1-4bd2-ae66-e0fd30de68ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7edfce20-1305-420e-ac0f-ccaf4838c0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUnit_Id</value>
      <webElementGuid>307bb6d8-4aa1-443a-a308-56c4fe84bfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>df665954-8c62-4b8e-98a3-63f33781381c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUnit_Id</value>
      <webElementGuid>0573f0da-6d24-4772-8856-54b51c79c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUnit_Id&quot;)</value>
      <webElementGuid>3f299300-9ab5-49b0-9f09-d593268afb7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUnit_Id']</value>
      <webElementGuid>dadaf457-e05b-4f76-87a0-ba4c009d34a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ohrmFormComponent_Form']/fieldset/ol/li/input[2]</value>
      <webElementGuid>b292b43b-9b83-4169-b5c4-956b7fbba66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input[2]</value>
      <webElementGuid>b898cbab-c155-456e-bdf5-66bb39a2dfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtUnit_Id' and @id = 'txtUnit_Id']</value>
      <webElementGuid>273110d7-f369-43a6-9bbb-d1e4d33282f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
