<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOGIN Panel_txtUsername</name>
   <tag></tag>
   <elementGuidId>2356a94e-03cf-4b70-970f-fde35148f8aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUsername']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtUsername</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ed47f96-a14f-44df-bdcb-5b8747090981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>c8cef846-f7db-4f5f-8172-ba53023fd76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUsername</value>
      <webElementGuid>4e2c5800-25ff-4283-b7d3-2aa3a24a1d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f931edd6-5f41-4673-95ab-455a73398743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUsername&quot;)</value>
      <webElementGuid>774f4d7a-5b2a-4f6c-bb12-1bd56a1b7d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUsername']</value>
      <webElementGuid>1a111d24-2d4a-41a5-84df-9fc4e4074bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divUsername']/input</value>
      <webElementGuid>a356015d-d92a-4baa-8535-4cd39ebff0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>47062359-d231-4a8d-8baf-ec8f83fc6822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtUsername' and @id = 'txtUsername' and @type = 'text']</value>
      <webElementGuid>3c5bb111-c3f6-4d43-a3c6-1e375378462b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
