<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Engineering</name>
   <tag></tag>
   <elementGuidId>d70dd8e7-6bd7-429d-aa5c-d428eaf25f53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#span_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66931826-9477-440e-9149-1b59e640a5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>span_3</value>
      <webElementGuid>c4c10099-61de-4ddb-8b4c-954c18effe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>labelNode</value>
      <webElementGuid>43d7a4f7-c029-41f9-a0a7-b5266faf6230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Engineering</value>
      <webElementGuid>f510b09e-18a3-40f1-a4f6-891be2e55497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_3&quot;)</value>
      <webElementGuid>7ebad347-1a15-47ab-ac92-e38850f54772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='span_3']</value>
      <webElementGuid>b56949f7-386e-4c4c-8a96-11aee66ecbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='node_3']/span</value>
      <webElementGuid>5bd4611f-76f8-4f78-adc3-9a932cade852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x'])[1]/following::span[1]</value>
      <webElementGuid>817e7a3e-1113-41c6-94c4-16455d5debd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/following::span[1]</value>
      <webElementGuid>9f8aa882-2ce2-4cc9-b06c-7f0b6b55cd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engineering'])[2]/preceding::span[1]</value>
      <webElementGuid>96f3b05c-205f-404e-8e0f-6fe4525bf084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[3]/preceding::span[1]</value>
      <webElementGuid>1653468c-fe7f-417f-9cf8-0a09da712914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Engineering']/parent::*</value>
      <webElementGuid>a322e1e9-3298-4f7a-a49e-f9025055eb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>ddb8746b-440f-4cb1-911f-04e3e048927f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'span_3' and (text() = 'Engineering' or . = 'Engineering')]</value>
      <webElementGuid>ae8762db-2f09-4bd0-89bc-20a3bd94a2f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
