<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Directory</name>
   <tag></tag>
   <elementGuidId>91ad3dfe-28c1-4bc2-9995-12682b9267b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_directory_viewDirectory > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_directory_viewDirectory']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>d74ca889-6e78-41de-afed-783cd3a4bcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Directory</value>
      <webElementGuid>3d907c63-0ae1-4b46-b2fa-7e19ab150bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_directory_viewDirectory&quot;)/b[1]</value>
      <webElementGuid>38221812-e378-4377-b315-c2fd7f4b55fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_directory_viewDirectory']/b</value>
      <webElementGuid>1478ba18-d5b5-4540-85ff-01c3103f9b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::b[1]</value>
      <webElementGuid>22c5793a-47d9-47d3-978a-8e53ec31df7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Trackers'])[1]/following::b[2]</value>
      <webElementGuid>6f51ee8e-131b-4804-b0b7-a5c9a983827f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buzz'])[1]/preceding::b[1]</value>
      <webElementGuid>8f5bc405-a3c2-42dd-994c-75fb27694eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::b[2]</value>
      <webElementGuid>e194b577-86b9-465e-80ed-a4dd44ef28b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Directory']/parent::*</value>
      <webElementGuid>2b92cc9d-6ef5-4e49-a79c-7bdf5b5a1633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/b</value>
      <webElementGuid>5c5946e3-d352-4bae-893f-6242a784b6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Directory' or . = 'Directory')]</value>
      <webElementGuid>1696b860-3a9b-4727-a1b8-5a1092854baf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
