<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_HR Manager_shareViewMoreMod1_22</name>
   <tag></tag>
   <elementGuidId>35d138af-6e54-4cc3-872e-ebee16990102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shareViewMoreMod1_22 > #shareViewMoreMod1_22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='shareViewMoreMod1_22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce3ecbbe-cd4e-4cf9-92f5-6ca262a8899a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hideModalPopUp</value>
      <webElementGuid>53bd9a7f-0e93-4bae-8a2f-35586e59d937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shareViewMoreMod1_22</value>
      <webElementGuid>29bfe7d8-5c13-4ee6-894b-26a50f419756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_625505b4d6d5f1.18812754/orangehrmBuzzPlugin/images/close.png</value>
      <webElementGuid>a80e2b51-6a13-4f97-bced-f8e7fe150e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0cf616e4-b24a-463b-ace1-86a708314488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8e8800a0-5752-4faf-beca-9883176b8d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postInList22&quot;)/div[@id=&quot;postBody&quot;]/div[@id=&quot;shareViewMoreMod1_22&quot;]/div[@class=&quot;modal-body viewMoreModal-body&quot;]/div[@id=&quot;shareViewMoreMod1_22&quot;]/img[@id=&quot;shareViewMoreMod1_22&quot;]</value>
      <webElementGuid>e8c8fad1-be5d-4e66-af52-77c98936cb32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='shareViewMoreMod1_22']</value>
      <webElementGuid>e983d99b-5fd0-4cc0-925a-2b233b951d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shareViewMoreMod1_22']/img</value>
      <webElementGuid>f64ab28a-a067-40bb-88ca-d5bb4014e6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[3]/div/div/img</value>
      <webElementGuid>11e20d94-4e4b-4cdf-947f-41d3848df3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'shareViewMoreMod1_22' and @src = '/webres_625505b4d6d5f1.18812754/orangehrmBuzzPlugin/images/close.png']</value>
      <webElementGuid>41d97001-3998-4e32-95a8-7a9b67db9fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
