<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_HR Manager_postLike_22</name>
   <tag></tag>
   <elementGuidId>dc6b9de1-0793-4e4b-bb4a-52694cc837c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postLikeno_22 > #postLike_22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='postLike_22'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0573279b-f1e9-47fc-8d6e-e5bc2bb8b3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/webres_625505b4d6d5f1.18812754/orangehrmBuzzPlugin/images/like/like.png</value>
      <webElementGuid>71a7f2b3-dafd-441b-abdd-744d29926bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b93f9750-c916-463d-b6cf-eb758c3b9aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postLike_22</value>
      <webElementGuid>a1b5a80e-7d80-4812-82f8-d3a790657332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Like postLike</value>
      <webElementGuid>66d830d1-ef58-47ed-b06f-76f0cb560dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ef7385d3-8a3b-4dd3-ba70-7fe841e2b9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>da7345b1-60a2-4da3-866b-3c92b5e1d189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postInList22&quot;)/div[@id=&quot;postBody&quot;]/div[@id=&quot;postBodyThirdRowNew&quot;]/div[@id=&quot;postLikebody_22&quot;]/a[@id=&quot;postLikeno_22&quot;]/img[@id=&quot;postLike_22&quot;]</value>
      <webElementGuid>61e0103e-16c4-469f-bd8a-54be1a4b0c0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='postLike_22'])[2]</value>
      <webElementGuid>e96ee48e-814d-4da2-aa9e-cb21951486ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='postLikeno_22']/img</value>
      <webElementGuid>5104f51a-7b66-4d85-b1c6-2b642351afb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>21212858-5be8-4a61-baa5-ce496e52900e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/webres_625505b4d6d5f1.18812754/orangehrmBuzzPlugin/images/like/like.png' and @id = 'postLike_22']</value>
      <webElementGuid>5d4e8811-1292-4cff-a6ef-1e859734b3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
