<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MajorSpecialization_educationmajor</name>
   <tag></tag>
   <elementGuidId>4ea0b146-8758-46a9-af30-d39a8df3f914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#education_major</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='education_major']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0baecc6-ade2-4947-94fd-7f774045cba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c928b22-180d-49ee-888f-14e66c2646e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>education[major]</value>
      <webElementGuid>4920e6c7-c4e1-4f41-8e36-35aaf4a595dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>bd1aab99-ce4b-42bd-ab29-dd5fa794b94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f5140722-26b4-403d-a234-00ffabfbc280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>education_major</value>
      <webElementGuid>26be19ea-a171-475d-9c98-400e650d3aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;education_major&quot;)</value>
      <webElementGuid>4708f5fc-f400-4754-b7ec-2b55855dc6af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='education_major']</value>
      <webElementGuid>70e6620e-431f-429e-b816-9885f3264cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEducation']/fieldset/ol/li[3]/input</value>
      <webElementGuid>fda2439f-b6f3-43c7-bd1d-32f179368441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/form/fieldset/ol/li[3]/input</value>
      <webElementGuid>1aa9d097-0e62-4f95-9304-b5ac27c1cba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'education[major]' and @id = 'education_major']</value>
      <webElementGuid>a6eb7401-e156-426c-8c79-7af0387c92a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
