<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Taken_btnSearch</name>
   <tag></tag>
   <elementGuidId>d6989e83-04c8-4782-bee7-884aac4c0ac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>565b53ff-b4b2-4299-91a8-071bd2b79875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aabffcc6-95b6-4429-b0c7-889e21ec055d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSearch</value>
      <webElementGuid>0f25ee6c-f4a6-4e64-867d-bab2be918528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9d670309-dd85-4fda-92b9-9b1ff2d6bd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSearch</value>
      <webElementGuid>371a16c4-8b67-4a1b-a03a-45a4e0f370a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plainbtn hover</value>
      <webElementGuid>f0e2bb3b-2653-48be-8324-d968495c36a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSearch&quot;)</value>
      <webElementGuid>b1062859-3ebc-435b-b595-3407ec36ef75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSearch']</value>
      <webElementGuid>1389dfce-6d45-4c99-9aca-fa24de05c913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmFilterLeave']/fieldset/p/input</value>
      <webElementGuid>fd0cd82c-c8bc-41cf-92fb-b4db64170454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>f189435a-255d-40b9-97e4-3e682bf13ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSearch' and @id = 'btnSearch']</value>
      <webElementGuid>f370639c-63e2-46a4-b5ca-e4f39f727140</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
