<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnEducationSave</name>
   <tag></tag>
   <elementGuidId>b40b32e1-e326-4f90-b2f1-6f0493d8113e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnEducationSave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnEducationSave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fe2f17b-a3dc-425b-a30b-82736d1328d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9da698ff-e430-4b08-85d4-73b91c7a37aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>e7ae0b07-c1a8-49ee-8bc3-71ff3f86ebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEducationSave</value>
      <webElementGuid>b84f26fb-4997-4a15-b063-5e90f7ac13ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>9c0b14e8-71e9-470a-9a8e-6372e6515fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEducationSave&quot;)</value>
      <webElementGuid>66db10e6-858a-43f9-b695-181df105439e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnEducationSave']</value>
      <webElementGuid>26aa81b1-2ba8-4f8d-91bc-05510b47961c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEducation']/fieldset/p/input</value>
      <webElementGuid>33b06913-ca47-4ee1-8ada-3376d34fea2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/form/fieldset/p/input</value>
      <webElementGuid>10a65435-92a4-45f7-aa9a-b5c7e4f61c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnEducationSave']</value>
      <webElementGuid>d2b366bd-8bcb-4ea1-b48c-c8adbd7358b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
