<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Education_addEducation</name>
   <tag></tag>
   <elementGuidId>09f1d2eb-54db-4d22-821e-8c4f8f8b9433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addEducation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addEducation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dc207a3-9fbd-4bd5-9890-89843b9b6dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76a9b637-e437-4384-a93f-1ececa0f7561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>1ce3cf5a-06b7-40ca-bcbb-0c9f040ca01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>41f338ee-0ff0-4192-a268-3e517cc4ae1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addEducation</value>
      <webElementGuid>0bc1e213-f1b3-48a2-8480-fce7c3d6d27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addEducation&quot;)</value>
      <webElementGuid>4faa76bd-4926-4403-8792-6f2a6fa88bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addEducation']</value>
      <webElementGuid>2de2bc94-3ae3-4383-8a5d-319fd7271d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='actionEducation']/input</value>
      <webElementGuid>4817f4e1-62a4-42b6-a8b3-92d09eb988aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p/input</value>
      <webElementGuid>53766e78-1bbc-40d9-9984-f106d03d2161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'addEducation']</value>
      <webElementGuid>22661de9-88c1-4963-be70-f597d349cbed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
