<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GPAScore_delEdu</name>
   <tag></tag>
   <elementGuidId>7417b25e-5f9a-47e0-b552-2fc0277fbda5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;delEdu[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='delEdu[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14e0165a-78b3-4ce4-8db9-30a1f1886934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f341bff3-35a1-4065-aeb4-24cb59a3c987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chkbox</value>
      <webElementGuid>94cc0e51-67ba-47a2-a172-dd053b2ef7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b4192904-cb49-4837-b356-767ace2e8615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delEdu[]</value>
      <webElementGuid>edc2b169-00c4-48f3-8568-9b9ad6dddcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblEducation&quot;)/table[@class=&quot;table tablesorter&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;check&quot;]/input[@class=&quot;chkbox&quot;]</value>
      <webElementGuid>1255509b-7157-4011-9f24-77ba9d2cd942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='delEdu[]']</value>
      <webElementGuid>6dcf7825-ef56-478b-a420-6e95597d9df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tblEducation']/table/tbody/tr/td/input[10]</value>
      <webElementGuid>b7e013d4-b75b-4fd8-bcf0-c15aac384284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>502517fd-db54-48ba-9dc1-52723dae2e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'delEdu[]']</value>
      <webElementGuid>3d77bb97-9ba7-4843-bebc-8205f2d8ee4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
