<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_searchDirectoryemp_nameempName</name>
   <tag></tag>
   <elementGuidId>f3c87b0e-3ce5-4cdc-bf8b-a7662aa9171c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchDirectory_emp_name_empName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchDirectory_emp_name_empName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84538f75-000b-4314-9d24-09e4f5657a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText ac_input</value>
      <webElementGuid>6489706d-61a1-4bf5-b175-64f213f8d724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a95b149c-2137-4700-b2d4-7648abb3f01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchDirectory[emp_name][empName]</value>
      <webElementGuid>73477843-9053-4557-9d82-427e205f9c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchDirectory_emp_name_empName</value>
      <webElementGuid>45a5a8f1-acbe-4867-a2c1-1e990e052ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>18c73681-4cf9-4173-b3f3-f4b7e153f273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchDirectory_emp_name_empName&quot;)</value>
      <webElementGuid>1e694bfd-000a-4c1b-8d75-4ff6596ad986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchDirectory_emp_name_empName']</value>
      <webElementGuid>30e99967-a39a-4f27-adaf-33b25faf3bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>9d1e0dda-2364-4840-b820-4ef3c5c6109e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>b3a11f8a-6a7b-4797-b189-3d44a47b73a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchDirectory[emp_name][empName]' and @id = 'searchDirectory_emp_name_empName']</value>
      <webElementGuid>66741e0d-9fce-4c40-ad18-fc888203ecf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
