<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_educationyear</name>
   <tag></tag>
   <elementGuidId>e37b2bc6-5955-42cf-a3dd-67b73306de51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#education_year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='education_year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6266031c-04d4-4460-846d-f9dadc4a56e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67f0985f-a5b2-48d2-b9d0-f57997e4841a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>education[year]</value>
      <webElementGuid>df84671e-3e64-48c8-bc16-0fc21b02c119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>fc452b78-7ce4-4fac-9e75-06070f2bd90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>bb0539e1-6bc2-474d-8ecb-60b35f742c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>education_year</value>
      <webElementGuid>6bfce114-06d4-4a69-b96e-e876c60d703e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;education_year&quot;)</value>
      <webElementGuid>e36c2590-7c3d-4cfe-8591-be2068bced1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='education_year']</value>
      <webElementGuid>f71b0b57-f3fe-486d-a652-22ed6fb5fd16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEducation']/fieldset/ol/li[4]/input</value>
      <webElementGuid>1175d616-fbd9-4567-ad6f-c96783e28ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/form/fieldset/ol/li[4]/input</value>
      <webElementGuid>c72355ba-99e1-46a9-9946-2b6c81a5c164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'education[year]' and @id = 'education_year']</value>
      <webElementGuid>1ecc69db-32b2-4818-8495-6ed55ab18739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
