<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sun                                 2_ad5757</name>
   <tag></tag>
   <elementGuidId>73aea343-ebd5-4f7d-becc-a92a18862659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#initialRows_0_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='initialRows_0_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25160375-100c-4b11-aae4-3f7455f22d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>a1a6e808-f6e6-4e3b-ad73-73e29e6bbc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>timeBox</value>
      <webElementGuid>90ce6db5-7ac2-4320-8c84-d2248db6723e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7e4ca266-6ace-4917-90fb-7c701e5138ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62a2d9e2-0362-468e-9b3e-6156466a8bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>initialRows[0][0]</value>
      <webElementGuid>14009f78-b389-405b-addb-524a60dd3d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>initialRows_0_0</value>
      <webElementGuid>79735123-0e12-4d9f-a379-ae94edcb009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initialRows_0_0&quot;)</value>
      <webElementGuid>dbee7ffe-f43f-4247-8b32-8909cc1a9c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='initialRows_0_0']</value>
      <webElementGuid>c16d242a-70aa-4752-af3d-0eda794229a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='timesheetForm']/div/table/tbody/tr/td[4]/input</value>
      <webElementGuid>8c455017-e298-4ffe-a60e-c06e0bbe3265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>7f484435-a49e-4d94-83eb-a91d33f4dfe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'initialRows[0][0]' and @id = 'initialRows_0_0']</value>
      <webElementGuid>2eefa31b-a15a-45f2-8cad-0d1a09ef6331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
