<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__view</name>
   <tag></tag>
   <elementGuidId>2d900f6e-f411-499d-97e6-d29a2c7bc46a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#viewBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='viewBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb42a737-8a91-43e5-8051-e9002e50aac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd0dae38-d1ff-427f-8558-387bc4d04c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>view</value>
      <webElementGuid>e4b8ee61-efad-468b-a00d-0388c9e1d87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewBtn</value>
      <webElementGuid>2438cc4b-3108-4b25-b8b7-bf7c3bce301a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>e8815207-375f-40cc-82bc-99404405a50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>b61e5724-b2e7-41f6-a94d-b3636d2d5941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewBtn&quot;)</value>
      <webElementGuid>0d251a02-5f07-40b1-b71d-f1c748aef007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='viewBtn']</value>
      <webElementGuid>280c9566-882f-4849-9801-47ee27c28d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLeaveBalanceReport']/fieldset/p/input</value>
      <webElementGuid>9cd900d5-fbc7-48c0-8085-7c0159472286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>b4a04799-be25-4e8c-8672-13dc34784a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'view' and @id = 'viewBtn']</value>
      <webElementGuid>d4bbc06d-dab6-4411-836f-17cae8c5cd2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
