<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Institute_educationinstitute</name>
   <tag></tag>
   <elementGuidId>3a72d2f4-ada5-4973-8de9-dff5e79dd953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#education_institute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='education_institute']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>402cf64d-ff34-447e-97e3-bf36431f438a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47011fcb-de8a-4c43-a399-dff29d0351c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>education[institute]</value>
      <webElementGuid>0abb6ce9-689a-4c13-9435-e76e9d612665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>37c5ab83-5810-4fbe-b057-0d142d6178af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>27e3c582-9778-42e2-826c-d5830dfac227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>education_institute</value>
      <webElementGuid>af5a1f4a-5e49-43eb-aa1e-f806f62a88e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;education_institute&quot;)</value>
      <webElementGuid>7d89dd3a-032d-451f-8f96-c10f091282cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='education_institute']</value>
      <webElementGuid>ac561800-ed59-44ba-8c8c-129f896f526f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEducation']/fieldset/ol/li[2]/input</value>
      <webElementGuid>2b5796be-b109-44b9-8d0b-e8b164a8ba21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/form/fieldset/ol/li[2]/input</value>
      <webElementGuid>73104bd0-11c6-4d20-afe2-826204989d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'education[institute]' and @id = 'education_institute']</value>
      <webElementGuid>35d33865-81ed-4abc-b62c-e395d4a89f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
